### ISSUE TITLE
ssh-dss removed in node 10

### ISSUE THREAD

**Issue by linusnorton** [mscdex/ssh2-streams#101]
It's possible it relates to the upgrade of openssl to version 1.1.0 but it seems `DSA-SHA1` is no longer listed in `crypto.getHashes()`. When I try to use it I get the error:

```
Error: Unknown message digest
    at new Verify (internal/crypto/sig.js:107:16)
    at Object.createVerify (crypto.js:133:10)
    at onKEXDH_REPLY (/home/linus/Work/opentrack/shared/dtd2mysql/node_modules/ssh2-streams/lib/ssh.js:2877:25)
    at SSH2Stream.<anonymous> (/home/linus/Work/opentrack/shared/dtd2mysql/node_modules/ssh2-streams/lib/ssh.js:215:45)
```
This causes the call to:

```
var verifier = crypto.createVerify(keyAlgo);
```

to fail.

**Comment by linusnorton** [comment]
Just as an update to this, if I rename DSA-SHA1 to DSS1 I can connect and do some commands.

**Comment by linusnorton** [comment]
@mscdex any chance the current master will be tagged?

**Comment by mpareja** [comment]
Leaving a breadcrumb of information here for anyone else using `ssh-dss` and getting `Error: Unknown message digest` after upgrading to node 10:

Just upgrade your version of ssh2 / ssh2-streams and it should correct the issue.
