### ISSUE TITLE
SFTP client fastPut error

### ISSUE THREAD

**Issue by sambengtson** [mscdex/ssh2-streams#11]
I can successfully connect to the server and get a directory listing, but when attempting to upload a file, I get a failure with the following stack trace with the following code:
```javascript
ftp.on('ready', function () {

    console.log('connection success');
    ftp.sftp(function (err, sftp) {
        if (err)
            throw err;

        sftp.fastPut(currentFile, '/', function (err) {
            if (err) throw err;
            console.log('done');
        });
    });
});
```
Error: Failure
    at SFTPStream._transform (C:\Users\sam.bengtson\Documents\NodeProjects\nodejs\tsm-usg-batch\node_modules\ssh2\node_modules\ssh2-streams\lib\sftp.js:354:27)
    at SFTPStream.Transform._read [as __read] (_stream_transform.js:179:10)
    at SFTPStream._read (C:\Users\sam.bengtson\Documents\NodeProjects\nodejs\tsm-usg-batch\node_modules\ssh2\node_modules\ssh2-streams\lib\sftp.js:160:15)
    at SFTPStream.Transform._write (_stream_transform.js:167:12)
    at doWrite (_stream_writable.js:301:12)
    at writeOrBuffer (_stream_writable.js:288:5)
    at SFTPStream.Writable.write (_stream_writable.js:217:11)
    at Channel.ondata (_stream_readable.js:540:20)
    at Channel.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)

Any thoughts?

**Comment by sambengtson** [comment]
I think I put this under the wrong project.  Disregard.
