### ISSUE TITLE
getting wierd error after client disconnects (winScp)

### ISSUE THREAD

**Issue by arthurvaverko** [mscdex/ssh2-streams#138]
all goes well until a client discinnects .. this is when the server crashes ..
and i cant find the reason :\

> ncaught error: { Error: write ECONNABORTED
>     at afterWriteDispatched (internal/stream_base_commons.js:78:25)
>     at writeGeneric (internal/stream_base_commons.js:73:3)
>     at Socket._writeGeneric (net.js:717:5)
>     at Socket._write (net.js:729:8)
>     at doWrite (_stream_writable.js:410:12)
>     at writeOrBuffer (_stream_writable.js:394:5)
>     at Socket.Writable.write (_stream_writable.js:294:11)
>     at SSH2Stream.ondata (_stream_readable.js:666:20)
>     at SSH2Stream.emit (events.js:182:13)
>     at addChunk (_stream_readable.js:283:12) errno: 'ECONNABORTED', code: 'ECONNABORTED', syscall: 'write' }

**Comment by arthurvaverko** [comment]
here are some debug logs.. 
looks like the server is trying to send an EOF but the client is already siconnecde .. 

> [2019-07-24T14:23:29.519] [DEBUG] SftpApiProxyServer - REALPATH req:[1552], return:[/]
> console.js:8
> [2019-07-24T14:23:29.521] [DEBUG] SftpApiProxyServer - [250592.49108499] DEBUG[SFTP]: Outgoing: Writing NAME
> console.js:8
> [2019-07-24T14:23:29.522] [DEBUG] SftpApiProxyServer - [250592.49108499] DEBUG: Outgoing: Writing CHANNEL_DATA (256)
> console.js:8
> [2019-07-24T14:23:29.524] [DEBUG] SftpApiProxyServer - [250592.49108499] DEBUG: Parser: IN_PACKET
> console.js:8
> [2019-07-24T14:23:29.525] [DEBUG] SftpApiProxyServer - [250592.49108499] DEBUG: Parser: Decrypting
> console.js:8

**Comment by mscdex** [comment]
You should be able to handle these by adding an `'error'` event handler.

**Comment by arthurvaverko** [comment]
On the sftpStream object, Session object or client object ? 

Also assuming ill handle and swallow the error, and manage to keep the server running..  any idea as to why this could happen ?

**Comment by mscdex** [comment]
The SFTPStream object.

As to why it's happening, it's hard to say. Is your server terminating the connection or is the client? If it's the latter, then there's not much that can be done since it is disconnecting seemingly abruptly.

**Comment by arthurvaverko** [comment]
So error event does not get caught when i subscribe to on 'error'

```typescript
export class SftpSessionHandler {

    private Logger: log4js.Logger;
    private IngestProfileDirectories: InMemoryDirectoryList;
    private ProfileDirectories: InMemoryDirectory[];
    private KalturaClient: KalturaClientWrapper;

    constructor(private authenticatedUser: AuthenticatedUser, private sftpStream: SFTPStream, ) {
        this.Logger = ServiceFactory.GetLogger("SftpApiProxyServer");
        this.KalturaClient = ServiceFactory.GetKalturaClient();

        this.sftpStream.on('REALPATH', async (reqId, path) => await this.onRealPath(reqId, path).catch((reason) => this.handleSftpError(reqId, reason)));
        this.sftpStream.on('SETSTAT', async (reqId, path, attrs) => await this.onSetStat(reqId, path, attrs).catch((reason) => this.handleSftpError(reqId, reason)));
        this.sftpStream.on('OPENDIR', async (reqId, path) => await this.OpenDir(reqId, path).catch((reason) => this.handleSftpError(reqId, reason)));
        this.sftpStream.on('READDIR', async (reqId, handle) => await this.onReadDir(reqId, handle).catch((reason) => this.handleSftpError(reqId, reason)));
        this.sftpStream.on('LSTAT', async (reqId, path) => await this.onLStat(reqId, path).catch((reason) => this.handleSftpError(reqId, reason)));
        this.sftpStream.on('OPEN', async (reqId, filename, flags, attrs) => await this.onOpen(reqId, filename, flags, attrs).catch((reason) => this.handleSftpError(reqId, reason)));
        this.sftpStream.on('WRITE', async (reqId, handle, offset, data) => await this.onWrite(reqId, handle, offset, data).catch((reason) => this.handleSftpError(reqId, reason)));
        this.sftpStream.on('REMOVE', async (reqId, path) => await this.onRemove(reqId, path).catch((reason) => this.handleSftpError(reqId, reason)));
        this.sftpStream.on('RENAME', async (reqId, oldPath, newPath) => await this.onRename(reqId, oldPath, newPath).catch((reason) => this.handleSftpError(reqId, reason)));
        this.sftpStream.on('CLOSE', async (reqId, handle) => await this.onClose(reqId, handle).catch((reason) => this.handleSftpError(reqId, reason)));

        this.sftpStream.on('FSETSTAT', async (reqId, handle) => await this.onFsetStat(reqId, handle).catch((reason) => this.handleSftpError(reqId, reason)));
        this.sftpStream.on('READ', async (reqId, handle, offset, length) => await this.onRead(reqId, handle, offset, length).catch((reason) => this.handleSftpError(reqId, reason)));
        this.sftpStream.on('STAT', async (reqId, path) => await this.onStat(reqId, path).catch((reason) => this.handleSftpError(reqId, reason)));

        this.sftpStream.on('close', async ()=> this.onDisconnectOrError(null));
        this.sftpStream.on('end', async ()=> this.onDisconnectOrError(null));
        this.sftpStream.on('error', async (err)=> this.onDisconnectOrError(err));
    }

....


public async onDisconnectOrError(err:any) {
        this.Logger.debug(`DISCONNECT OR ERROR user:[${this.authenticatedUser.username}]`);
        this.Logger.error('ERROR:',err);
        this.sftpStream.end();
    }

``` 

I don't see the log message ..

**Comment by arthurvaverko** [comment]
well workaround works by attaching to 

`client.on('error', (err) => { this.Logger.error("client err...", err); });`
