### ISSUE TITLE
bundling ssh2-streams with Browserify not longer possible 

### ISSUE THREAD

**Issue by Thorsten-SCE** [mscdex/ssh2-streams#142]
ssh2-streams can no longer be bundled with Browserify (probably it is not limited to Browserify). 
__dirname points to the path of the bundled javascript and thus all required statements that refer to it fail.

lib/buffer-helpers.js could not be found (constants.js and jsbn.js as well)

```
Error: Cannot find module '.../ssh_auth/node_modules/ssh2-streams/lib./buffer-helpers'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
```

The solution seems to be rather simple. 

current: 
```
var bufferHelpers = require(__dirname + './buffer-helpers'); 
var constants = require(__dirname + '/constants');
var BigInteger = require(__dirname + '/jsbn.js');
```

new: 
```
var bufferHelpers = require('./buffer-helpers');
var constants = require('./constants');
var BigInteger = require('./jsbn.js');
```

best regards
Thorsten

**Comment by Thorsten-SCE** [comment]
Issue is already solved with commit from Mariusz Nowak on 12.03.19.

That's great :-)

When are you planning a new release? (I hope someone reads this...)
