### ISSUE TITLE
TypeError: utils.readString is not a function

### ISSUE THREAD

**Issue by diwic** [mscdex/ssh2-streams#155]
Hi,

I'm getting this error, but only when running under `jest`, so I'm not sure if the problem is with this library or with `jest` itself.

    TypeError: utils.readString is not a function
    at Function.OpenSSH_Private.parse (....\node_modules\ssh2-streams\lib\keyParser.js:525:28)
    at parseKey (....\node_modules\ssh2-streams\lib\keyParser.js:1440:32)
    at new Server (....\node_modules\ssh2\lib\server.js:45:20)

I tried debug printing:

    // avoid cyclic require by requiring on first use
    console.error("utils before:", utils);
    if (!utils)
      utils = require('./utils.js');
    console.error("utils after:", utils);
    var cipherName = utils.readString(data, 15, 'ascii');

And the result was:

    utils before: undefined
    utils after: {}

**Comment by diwic** [comment]
Okay, and now the problem went away, just as mysterious as it arrived.
