### ISSUE TITLE
Inconsistent error "Invalid HMAC"

### ISSUE THREAD

**Issue by domosapien** [mscdex/ssh2-streams#46]
I have a server that opens 3 connections to 3 different clients and runs a command. Randomly the server will throw the following error:
```
ERROR Error: Invalid HMAC
  at SSH2Stream._transform (.../node_modules/ssh2-streams/lib/ssh.js:543:25)
  at SSH2Stream.Transform._read (_stream_transform.js:167:10)
  at SSH2Stream._read (.../node_modules/ssh2-streams/lib/ssh.js:236:15)
  at SSH2Stream.Transform._write (_stream_transform.js:155:12)
  at doWrite (_stream_writable.js:307:12)
  at writeOrBuffer (_stream_writable.js:293:5)
  at SSH2Stream.Writable.write (_stream_writable.js:220:11)
  at Socket.ondata (_stream_readable.js:556:20)
  at emitOne (events.js:96:13)
  at Socket.emit (events.js:188:7)
  at readableAddChunk (_stream_readable.js:177:18)
  at Socket.Readable.push (_stream_readable.js:135:10)
  at TCP.onread (net.js:542:20)
```
It doesn't happen every time it's run and it doesn't happen on all servers at the same time (sometimes 0, 1, 2, or all 3). The command is long running (5-10 mins) with a lot of output (thousands of lines), and logging shows it happens to stop randomly in time/code for that command.

Server:
```
# node --version
v6.4.0
# ssh -V
OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.8, OpenSSL 1.0.1f 6 Jan 2014
# npm ls ssh2-streams
...
└─┬ ssh2@0.5.0
  └── ssh2-streams@0.1.6
```
Clients:
```
# ssh -V
OpenSSH_5.3p1, OpenSSL 0.9.8e-fips-rhel5 01 Jul 2008
# ssh -V
OpenSSH_5.3p1, OpenSSL 1.0.1e-fips 11 Feb 2013
# ssh -V
OpenSSH_6.6.1p1, OpenSSL 1.0.1e-fips 11 Feb 2013

```

**Comment by domosapien** [comment]
As some background, this library/process had been working flawlessly up to a couple weeks ago. I updated all the associated libraries on both server/client to no avail. It is possibly correlated to updating node from v0.10 to v6, but that may be a red herring.

**Comment by mscdex** [comment]
Can you set `debug: console.log` in the connection config and post the handshaking info (where the ciphers, hmacs, etc. are exchanged) for each of the problematic endpoints?

**Comment by domosapien** [comment]
We have a giant log that doesn't separate the output on the server (internal tool, logging not normally needed to be separate), so apologies for that. Here is all 3:
```
Local ident: 'SSH-2.0-ssh2js0.1.6'
Client: Trying build5.dev.teralogics.com on port 22 ...
Local ident: 'SSH-2.0-ssh2js0.1.6'
Client: Trying build6.dev.teralogics.com on port 22 ...
Local ident: 'SSH-2.0-ssh2js0.1.6'
Client: Trying build7.dev.teralogics.com on port 22 ...
Client: Connected
Client: Connected
Client: Connected
Parser: IN_INIT
Parser: IN_GREETING
Parser: IN_HEADER
Remote ident: 'SSH-2.0-OpenSSH_5.3'
Parser: IN_INIT
Parser: IN_GREETING
Parser: IN_HEADER
Remote ident: 'SSH-2.0-OpenSSH_6.6.1'
Outgoing: Writing KEXINIT
Parser: IN_PACKETBEFORE (expecting 8)
Parser: IN_PACKET
Parser: pktLen:780,padLen:10,remainLen:776
Parser: IN_PACKETDATA
Parser: IN_PACKETDATAAFTER, packet: KEXINIT
Comparing KEXINITs ...
(local) KEX algorithms: ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha1
(remote) KEX algorithms: diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
KEX algorithm: diffie-hellman-group-exchange-sha256
(local) Host key formats: ssh-rsa,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521
(remote) Host key formats: ssh-rsa,ssh-dss
Host key format: ssh-rsa
(local) Client->Server ciphers: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com
(remote) Client->Server ciphers: aes128-ctr,aes192-ctr,aes256-ctr,arcfour256,arcfour128,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,aes192-cbc,aes256-cbc,arcfour,rijndael-cbc@lysator.liu.se
Client->Server Cipher: aes128-ctr
(local) Server->Client ciphers: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com
(remote) Server->Client ciphers: aes128-ctr,aes192-ctr,aes256-ctr,arcfour256,arcfour128,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,aes192-cbc,aes256-cbc,arcfour,rijndael-cbc@lysator.liu.se
Server->Client Cipher: aes128-ctr
(local) Client->Server HMAC algorithms: hmac-sha2-256,hmac-sha2-512,hmac-sha1
(remote) Client->Server HMAC algorithms: hmac-md5,hmac-sha1,umac-64@openssh.com,hmac-ripemd160,hmac-ripemd160@openssh.com,hmac-sha1-96,hmac-md5-96
Client->Server HMAC algorithm: hmac-sha1
(local) Server->Client HMAC algorithms: hmac-sha2-256,hmac-sha2-512,hmac-sha1
(remote) Server->Client HMAC algorithms: hmac-md5,hmac-sha1,umac-64@openssh.com,hmac-ripemd160,hmac-ripemd160@openssh.com,hmac-sha1-96,hmac-md5-96
Server->Client HMAC algorithm: hmac-sha1
(local) Client->Server compression algorithms: none,zlib@openssh.com,zlib
(remote) Client->Server compression algorithms: none,zlib@openssh.com
Client->Server compression algorithm: none
(local) Server->Client compression algorithms: none,zlib@openssh.com,zlib
(remote) Server->Client compression algorithms: none,zlib@openssh.com
Server->Client compression algorithm: none
Outgoing: Writing KEXDH_GEX_REQUEST
Parser: IN_PACKETBEFORE (expecting 8)
Outgoing: Writing KEXINIT
Parser: IN_PACKETBEFORE (expecting 8)
Parser: IN_PACKET
Parser: pktLen:1636,padLen:10,remainLen:1632
Parser: IN_PACKETDATA
Parser: IN_PACKETDATAAFTER, packet: KEXINIT
Comparing KEXINITs ...
(local) KEX algorithms: ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha1
(remote) KEX algorithms: curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
KEX algorithm: ecdh-sha2-nistp256
(local) Host key formats: ssh-rsa,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521
(remote) Host key formats: ssh-rsa,ecdsa-sha2-nistp256,ssh-ed25519
Host key format: ssh-rsa
(local) Client->Server ciphers: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com
(remote) Client->Server ciphers: aes128-ctr,aes192-ctr,aes256-ctr,arcfour256,arcfour128,aes128-gcm@openssh.com,aes256-gcm@openssh.com,chacha20-poly1305@openssh.com,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,aes192-cbc,aes256-cbc,arcfour,rijndael-cbc@lysator.liu.se
Client->Server Cipher: aes128-ctr
(local) Server->Client ciphers: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com
(remote) Server->Client ciphers: aes128-ctr,aes192-ctr,aes256-ctr,arcfour256,arcfour128,aes128-gcm@openssh.com,aes256-gcm@openssh.com,chacha20-poly1305@openssh.com,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,aes192-cbc,aes256-cbc,arcfour,rijndael-cbc@lysator.liu.se
Server->Client Cipher: aes128-ctr
(local) Client->Server HMAC algorithms: hmac-sha2-256,hmac-sha2-512,hmac-sha1
(remote) Client->Server HMAC algorithms: hmac-md5-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-ripemd160-etm@openssh.com,hmac-sha1-96-etm@openssh.com,hmac-md5-96-etm@openssh.com,hmac-md5,hmac-sha1,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-ripemd160,hmac-ripemd160@openssh.com,hmac-sha1-96,hmac-md5-96
Client->Server HMAC algorithm: hmac-sha2-256
(local) Server->Client HMAC algorithms: hmac-sha2-256,hmac-sha2-512,hmac-sha1
(remote) Server->Client HMAC algorithms: hmac-md5-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-ripemd160-etm@openssh.com,hmac-sha1-96-etm@openssh.com,hmac-md5-96-etm@openssh.com,hmac-md5,hmac-sha1,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-ripemd160,hmac-ripemd160@openssh.com,hmac-sha1-96,hmac-md5-96
Server->Client HMAC algorithm: hmac-sha2-256
(local) Client->Server compression algorithms: none,zlib@openssh.com,zlib
(remote) Client->Server compression algorithms: none,zlib@openssh.com
Client->Server compression algorithm: none
(local) Server->Client compression algorithms: none,zlib@openssh.com,zlib
(remote) Server->Client compression algorithms: none,zlib@openssh.com
Server->Client compression algorithm: none
Outgoing: Writing KEXECDH_INIT
Parser: IN_PACKETBEFORE (expecting 8)
Parser: IN_INIT
Parser: IN_GREETING
Parser: IN_HEADER
Remote ident: 'SSH-2.0-OpenSSH_5.3'
Outgoing: Writing KEXINIT
Parser: IN_PACKETBEFORE (expecting 8)
Parser: IN_PACKET
Parser: pktLen:836,padLen:10,remainLen:832
Parser: IN_PACKETDATA
Parser: IN_PACKETDATAAFTER, packet: KEXINIT
Comparing KEXINITs ...
(local) KEX algorithms: ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha1
(remote) KEX algorithms: diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
KEX algorithm: diffie-hellman-group-exchange-sha256
(local) Host key formats: ssh-rsa,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521
(remote) Host key formats: ssh-rsa,ssh-dss
Host key format: ssh-rsa
(local) Client->Server ciphers: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com
(remote) Client->Server ciphers: aes128-ctr,aes192-ctr,aes256-ctr,arcfour256,arcfour128,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,aes192-cbc,aes256-cbc,arcfour,rijndael-cbc@lysator.liu.se
Client->Server Cipher: aes128-ctr
(local) Server->Client ciphers: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com
(remote) Server->Client ciphers: aes128-ctr,aes192-ctr,aes256-ctr,arcfour256,arcfour128,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,aes192-cbc,aes256-cbc,arcfour,rijndael-cbc@lysator.liu.se
Server->Client Cipher: aes128-ctr
(local) Client->Server HMAC algorithms: hmac-sha2-256,hmac-sha2-512,hmac-sha1
(remote) Client->Server HMAC algorithms: hmac-md5,hmac-sha1,umac-64@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-ripemd160,hmac-ripemd160@openssh.com,hmac-sha1-96,hmac-md5-96
Client->Server HMAC algorithm: hmac-sha2-256
(local) Server->Client HMAC algorithms: hmac-sha2-256,hmac-sha2-512,hmac-sha1
(remote) Server->Client HMAC algorithms: hmac-md5,hmac-sha1,umac-64@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-ripemd160,hmac-ripemd160@openssh.com,hmac-sha1-96,hmac-md5-96
Server->Client HMAC algorithm: hmac-sha2-256
(local) Client->Server compression algorithms: none,zlib@openssh.com,zlib
(remote) Client->Server compression algorithms: none,zlib@openssh.com
Client->Server compression algorithm: none
(local) Server->Client compression algorithms: none,zlib@openssh.com,zlib
(remote) Server->Client compression algorithms: none,zlib@openssh.com
Server->Client compression algorithm: none
```

**Comment by domosapien** [comment]
Client 1:
```
Local ident: 'SSH-2.0-ssh2js0.1.6'
Client: Trying ... on port 22 ...
Client: Connected
Remote ident: 'SSH-2.0-OpenSSH_5.3'
Outgoing: Writing KEXINIT
Comparing KEXINITs ...
(local) KEX algorithms: ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha1
(remote) KEX algorithms: diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
KEX algorithm: diffie-hellman-group-exchange-sha256
(local) Host key formats: ssh-rsa,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521
(remote) Host key formats: ssh-rsa,ssh-dss
Host key format: ssh-rsa
(local) Client->Server ciphers: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com
(remote) Client->Server ciphers: aes128-ctr,aes192-ctr,aes256-ctr,arcfour256,arcfour128,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,aes192-cbc,aes256-cbc,arcfour,rijndael-cbc@lysator.liu.se
Client->Server Cipher: aes128-ctr
(local) Server->Client ciphers: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com
(remote) Server->Client ciphers: aes128-ctr,aes192-ctr,aes256-ctr,arcfour256,arcfour128,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,aes192-cbc,aes256-cbc,arcfour,rijndael-cbc@lysator.liu.se
Server->Client Cipher: aes128-ctr
(local) Client->Server HMAC algorithms: hmac-sha2-256,hmac-sha2-512,hmac-sha1
(remote) Client->Server HMAC algorithms: hmac-md5,hmac-sha1,umac-64@openssh.com,hmac-ripemd160,hmac-ripemd160@openssh.com,hmac-sha1-96,hmac-md5-96
Client->Server HMAC algorithm: hmac-sha1
(local) Server->Client HMAC algorithms: hmac-sha2-256,hmac-sha2-512,hmac-sha1
(remote) Server->Client HMAC algorithms: hmac-md5,hmac-sha1,umac-64@openssh.com,hmac-ripemd160,hmac-ripemd160@openssh.com,hmac-sha1-96,hmac-md5-96
Server->Client HMAC algorithm: hmac-sha1
(local) Client->Server compression algorithms: none,zlib@openssh.com,zlib
(remote) Client->Server compression algorithms: none,zlib@openssh.com
Client->Server compression algorithm: none
(local) Server->Client compression algorithms: none,zlib@openssh.com,zlib
(remote) Server->Client compression algorithms: none,zlib@openssh.com
Server->Client compression algorithm: none
Outgoing: Writing KEXDH_GEX_REQUEST
Outgoing: Writing KEXDH_GEX_INIT
Checking host key format
Checking signature format
Verifying host fingerprint
Host accepted by default (no verification)
Verifying signature
Outgoing: Writing NEWKEYS
Outgoing: Writing SERVICE_REQUEST (ssh-userauth)
Outgoing: Writing USERAUTH_REQUEST (password)
Outgoing: Writing CHANNEL_OPEN (0, session)
Outgoing: Writing CHANNEL_REQUEST (0, exec)
```
Client 2:
```
Local ident: 'SSH-2.0-ssh2js0.1.6'
Client: Trying ... on port 22 ...
Client: Connected
Remote ident: 'SSH-2.0-OpenSSH_5.3'
Outgoing: Writing KEXINIT
Comparing KEXINITs ...
(local) KEX algorithms: ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha1
(remote) KEX algorithms: diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
KEX algorithm: diffie-hellman-group-exchange-sha256
(local) Host key formats: ssh-rsa,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521
(remote) Host key formats: ssh-rsa,ssh-dss
Host key format: ssh-rsa
(local) Client->Server ciphers: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com
(remote) Client->Server ciphers: aes128-ctr,aes192-ctr,aes256-ctr,arcfour256,arcfour128,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,aes192-cbc,aes256-cbc,arcfour,rijndael-cbc@lysator.liu.se
Client->Server Cipher: aes128-ctr
(local) Server->Client ciphers: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com
(remote) Server->Client ciphers: aes128-ctr,aes192-ctr,aes256-ctr,arcfour256,arcfour128,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,aes192-cbc,aes256-cbc,arcfour,rijndael-cbc@lysator.liu.se
Server->Client Cipher: aes128-ctr
(local) Client->Server HMAC algorithms: hmac-sha2-256,hmac-sha2-512,hmac-sha1
(remote) Client->Server HMAC algorithms: hmac-md5,hmac-sha1,umac-64@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-ripemd160,hmac-ripemd160@openssh.com,hmac-sha1-96,hmac-md5-96
Client->Server HMAC algorithm: hmac-sha2-256
(local) Server->Client HMAC algorithms: hmac-sha2-256,hmac-sha2-512,hmac-sha1
(remote) Server->Client HMAC algorithms: hmac-md5,hmac-sha1,umac-64@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-ripemd160,hmac-ripemd160@openssh.com,hmac-sha1-96,hmac-md5-96
Server->Client HMAC algorithm: hmac-sha2-256
(local) Client->Server compression algorithms: none,zlib@openssh.com,zlib
(remote) Client->Server compression algorithms: none,zlib@openssh.com
Client->Server compression algorithm: none
(local) Server->Client compression algorithms: none,zlib@openssh.com,zlib
(remote) Server->Client compression algorithms: none,zlib@openssh.com
Server->Client compression algorithm: none
Outgoing: Writing KEXDH_GEX_REQUEST
Outgoing: Writing KEXDH_GEX_INIT
Checking host key format
Checking signature format
Verifying host fingerprint
Host accepted by default (no verification)
Verifying signature
Outgoing: Writing NEWKEYS
Outgoing: Writing SERVICE_REQUEST (ssh-userauth)
Outgoing: Writing USERAUTH_REQUEST (password)
Outgoing: Writing CHANNEL_OPEN (0, session)
Outgoing: Writing CHANNEL_REQUEST (0, exec)
```
Client 3:
```
Local ident: 'SSH-2.0-ssh2js0.1.6'
Client: Trying ... on port 22 ...
Client: Connected
Remote ident: 'SSH-2.0-OpenSSH_6.6.1'
Outgoing: Writing KEXINIT
Comparing KEXINITs ...
(local) KEX algorithms: ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha1
(remote) KEX algorithms: curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
KEX algorithm: ecdh-sha2-nistp256
(local) Host key formats: ssh-rsa,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521
(remote) Host key formats: ssh-rsa,ecdsa-sha2-nistp256,ssh-ed25519
Host key format: ssh-rsa
(local) Client->Server ciphers: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com
(remote) Client->Server ciphers: aes128-ctr,aes192-ctr,aes256-ctr,arcfour256,arcfour128,aes128-gcm@openssh.com,aes256-gcm@openssh.com,chacha20-poly1305@openssh.com,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,aes192-cbc,aes256-cbc,arcfour,rijndael-cbc@lysator.liu.se
Client->Server Cipher: aes128-ctr
(local) Server->Client ciphers: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm,aes128-gcm@openssh.com,aes256-gcm,aes256-gcm@openssh.com
(remote) Server->Client ciphers: aes128-ctr,aes192-ctr,aes256-ctr,arcfour256,arcfour128,aes128-gcm@openssh.com,aes256-gcm@openssh.com,chacha20-poly1305@openssh.com,aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,aes192-cbc,aes256-cbc,arcfour,rijndael-cbc@lysator.liu.se
Server->Client Cipher: aes128-ctr
(local) Client->Server HMAC algorithms: hmac-sha2-256,hmac-sha2-512,hmac-sha1
(remote) Client->Server HMAC algorithms: hmac-md5-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-ripemd160-etm@openssh.com,hmac-sha1-96-etm@openssh.com,hmac-md5-96-etm@openssh.com,hmac-md5,hmac-sha1,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-ripemd160,hmac-ripemd160@openssh.com,hmac-sha1-96,hmac-md5-96
Client->Server HMAC algorithm: hmac-sha2-256
(local) Server->Client HMAC algorithms: hmac-sha2-256,hmac-sha2-512,hmac-sha1
(remote) Server->Client HMAC algorithms: hmac-md5-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-ripemd160-etm@openssh.com,hmac-sha1-96-etm@openssh.com,hmac-md5-96-etm@openssh.com,hmac-md5,hmac-sha1,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-ripemd160,hmac-ripemd160@openssh.com,hmac-sha1-96,hmac-md5-96
Server->Client HMAC algorithm: hmac-sha2-256
(local) Client->Server compression algorithms: none,zlib@openssh.com,zlib
(remote) Client->Server compression algorithms: none,zlib@openssh.com
Client->Server compression algorithm: none
(local) Server->Client compression algorithms: none,zlib@openssh.com,zlib
(remote) Server->Client compression algorithms: none,zlib@openssh.com
Server->Client compression algorithm: none
Outgoing: Writing KEXECDH_INIT
Checking host key format
Checking signature format
Verifying host fingerprint
Host accepted by default (no verification)
Verifying signature
Outgoing: Writing NEWKEYS
Outgoing: Writing SERVICE_REQUEST (ssh-userauth)
Outgoing: Writing USERAUTH_REQUEST (password)
Outgoing: Writing CHANNEL_OPEN (0, session)
Outgoing: Writing CHANNEL_REQUEST (0, exec)
```

**Comment by domosapien** [comment]
@mscdex Anything else I can try to help debug?

**Comment by mscdex** [comment]
Is there some example code you could give to reproduce this? I cannot reproduce it on my end by generating lots of lines of text remotely.

**Comment by domosapien** [comment]
Unfortunately I can't give you specific examples (my company is against it), but essentially we had a bot responding to irc commands that then connected using this library to different servers that ran a grunt script which ran commands to build an rpm on different OSes (which generated a lot of output). We have since switched our build process to be completely different and use integrated CI tools so I can be of little help in debugging further.
