### ISSUE TITLE
installation complete or not?

### ISSUE THREAD

**Issue by scheung38** [mscdex/ssh2-streams#49]
$ npm install ssh2-streams
spark2acs@1.0.0 /Users/sebastien.cheung/spark2acs
├── UNMET PEER DEPENDENCY react@15.3.1
└── ssh2-streams@0.1.7 

npm WARN formsy-react@0.17.0 requires a peer of react@^0.14.0 but none was installed.

Does it mean it is installed or not?

which ssh2-streams returns empty?

Because when doing a MeteorJS mupx setup:

$ mupx setup

Meteor Up: Production Quality Meteor Deployments
------------------------------------------------
Configuration file : mup.json
Settings file      : settings.json

“ Checkout Kadira!
  It's the best way to monitor performance of your app.
  Visit: https://kadira.io/mup ”

Started TaskList: Setup (linux)
[46.101.86.130] - Installing Docker
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: All configured authentication methods failed
    at tryNextAuth (/usr/local/lib/node_modules/mupx/node_modules/ssh2/lib/client.js:290:17)
    at SSH2Stream.onUSERAUTH_FAILURE (/usr/local/lib/node_modules/mupx/node_modules/ssh2/lib/client.js:469:5)
    at emitTwo (events.js:87:13)
    at SSH2Stream.emit (events.js:172:7)
    at parsePacket (/usr/local/lib/node_modules/mupx/node_modules/ssh2-streams/lib/ssh.js:3647:10)
    at SSH2Stream._transform (/usr/local/lib/node_modules/mupx/node_modules/ssh2-streams/lib/ssh.js:551:13)
    at SSH2Stream.Transform._read (_stream_transform.js:167:10)
    at SSH2Stream._read (/usr/local/lib/node_modules/mupx/node_modules/ssh2-streams/lib/ssh.js:212:15)
    at SSH2Stream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:300:12)

**Comment by mscdex** [comment]
It's working fine, you just have an authentication problem.

**Comment by mscdex** [comment]
Also, you don't need to install `ssh2-streams` manually, since it's used as a dependency of `mupx` apparently. You should contact the maintainer(s) of `mupx` about adding error handlers in order to handle errors more gracefully.
