### ISSUE TITLE
SFTP Error: java.lang.NullPointerException

### ISSUE THREAD

**Issue by adampatarino** [mscdex/ssh2-streams#64]
I'm using sftp.fastPut and with files over a few KB I'm routinely getting the following exception thrown: 

```
Error: java.lang.NullPointerException
    at SFTPStream._transform (/Users/adam/Projects/Emarsys/nodeETL/node_modules/ssh2-streams/lib/sftp.js:405:27)
    at SFTPStream.Transform._read (_stream_transform.js:167:10)
    at SFTPStream._read (/Users/adam/Projects/Emarsys/nodeETL/node_modules/ssh2-streams/lib/sftp.js:181:15)
    at SFTPStream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:332:12)
    at clearBuffer (_stream_writable.js:439:7)
    at onwrite (_stream_writable.js:371:7)
    at afterTransform (_stream_transform.js:79:3)
    at TransformState.afterTransform (_stream_transform.js:54:12)
    at SFTPStream._transform (/Users/adam/Projects/Emarsys/nodeETL/node_modules/ssh2-streams/lib/sftp.js:745:3)
    at SFTPStream.Transform._read (_stream_transform.js:167:10)
    at SFTPStream._read (/Users/adam/Projects/Emarsys/nodeETL/node_modules/ssh2-streams/lib/sftp.js:181:15)
    at SFTPStream.Readable.read (_stream_readable.js:348:10)
    at flow (_stream_readable.js:761:34)
    at Channel.<anonymous> (_stream_readable.js:623:7)
    at emitNone (events.js:86:13) code: 4, lang: '' }
```

I can't figure out what about the file / code is causing the exception as the stack trace is not very helpful. Here's the relevant bit of code:

```javascript
return new Promise(function(resolve,reject) {
    conn.on('ready', function(){
        console.log('connected to upload server');
        conn.sftp(function(err,sftp) {
            if(err) return reject(err);
            console.log('sftp started on uploaded');

            sftp.fastPut(get,put,function(err) {
                sftp.end();
                conn.end();
                if(err) return reject(err);
                console.log('upload callback');
                console.timeEnd('promise');
                resolve({
                    local: get,
                    remote: put
                });
            })
        });
    }).connect(self.credentials);
});
```

Any ideas or suggestions on what might be causing the issue? It seems to occur on the third _write iteration as two chunks are written and the third causes the exception.

**Comment by adampatarino** [comment]
Worth noting, I do not get an error when using `sftp.createWriteStream()` on the same file.

**Comment by mscdex** [comment]
Sounds like a server issue? The 'java.lang.NullPointerException' error message is coming directly from the sftp server.

**Comment by adampatarino** [comment]
Ok yeah, that makes sense. I'm just going to use read and write streams, rather than fastPut. Thank you!
