### ISSUE TITLE
Error: com.jcraft.jsch.JSchException: Auth fail at onDISCONNECT

### ISSUE THREAD

**Issue by tkambler** [mscdex/ssh2-streams#82]
First - thank you for the substantial amount of work you've put in on this library. It is tremendously useful.

I've put together a server for the sole purpose of accepting SFTP connections:

https://github.com/tkambler/sftp-server

I'm still getting familiar with the various stream classes, and I've yet to determine the source of the following error that I'm frequently seeing show up in my logs. If you could point me in the right direction, I would really appreciate it.

```
Error: com.jcraft.jsch.JSchException: Auth fail\n    at onDISCONNECT 
(/home/ubuntu/sftp/node_modules/ssh2-streams/lib/ssh.js:2201:15)\n    at SSH2Stream.
<anonymous> (/home/ubuntu/sftp/node_modules/ssh2-streams/lib/ssh.js:203:5)\n    at emitMany 
(events.js:127:13)\n    at SSH2Stream.emit (events.js:201:7)\n    at parsePacket 
(/home/ubuntu/sftp/node_modules/ssh2-streams/lib/ssh.js:3747:10)\n    at 
SSH2Stream._transform (/home/ubuntu/sftp/node_modules/ssh2-streams/lib/ssh.js:668:13)\n    at 
SSH2Stream.Transform._read (_stream_transform.js:167:10)\n    at SSH2Stream._read 
(/home/ubuntu/sftp/node_modules/ssh2-streams/lib/ssh.js:251:15)\n    at 
SSH2Stream.Transform._write (_stream_transform.js:155:12)\n    at doWrite 
(_stream_writable.js:334:12)\n    at writeOrBuffer (_stream_writable.js:320:5)\n    at 
SSH2Stream.Writable.write (_stream_writable.js:247:11)\n    at Socket.ondata 
(_stream_readable.js:555:20)\n    at emitOne (events.js:96:13)\n    at Socket.emit 
(events.js:188:7)\n    at readableAddChunk (_stream_readable.js:176:18)\n    at 
Socket.Readable.push (_stream_readable.js:134:10)\n    at TCP.onread (net.js:548:20)
```

**Comment by mscdex** [comment]
Add an `'error'` event handler on the client object.

The client is sending a non-typical/non-"OK" disconnect status, this is the reason for the error event.

**Comment by tkambler** [comment]
> Add an `'error'` event handler on the client object.

I've already done that:

```
new ssh2.Server({
    'hostKeys': '...',
    'algorithms': '...'
}, (client) => {

    client
        .on('authentication', (authContext) => {
            // ...
        })
        .on('ready', () => {
            // ...
        })
        .on('end', () => {
            // ...
        })
        .on('continue', () => {
            // ...
        })
        .on('rekey', () => {
            // ...
        })
        .on('tcpip', (accept, reject) => {
            // ...
        })
        .on('openssh.streamlocal', (accept, reject, info) => {
            // ...
        })
        .on('request', (accept, reject, name, info) => {
            // ...
        })
        .on('close', (hadError) => {
            // ...
        })
        .on('error', (err) => {
            // ...
        });

});
```

Thank you for the swift response.

**Comment by mscdex** [comment]
There's not much you can do over and above that. The ultimate cause has to do with user authentication failing. It's just that this client is being "loud" about it and sending a different disconnect status.

**Comment by tkambler** [comment]
Thanks for the heads up. 👍
