### ISSUE TITLE
keyParser.js:42

### ISSUE THREAD

**Issue by Masyno** [mscdex/ssh2-streams#90]
just, i need help...
```

  while (!data[0].length)
                 ^

TypeError: Cannot read property 'length' of undefined
    at module.exports (D:\Development\Telnet\node_modules\ssh2-streams\lib\keyParser.js:42:18)
    at new Server (D:\Development\Telnet\node_modules\ssh2\lib\server.js:45:20)
    at Object.<anonymous> (D:\Development\Telnet\test.js:49:1)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
```

**Comment by mscdex** [comment]
This error should never occur. Splitting a string should *always* return an array with at least one element.

Are you using any other third-party modules (that might be mutating built-in JavaScript functions)? If so, try to remove them one by one to see if that changes things.

**Comment by yaapis** [comment]
Same error here. I've tried node8 and node10 (in docker container) - both raise same error. In my local env everything works as expected. 
@mscdex Do you have this issue fixed?

**Comment by yaapis** [comment]
OK. As it always happens, I've found out the issue just after posting my question =)
My mistake was in variable typings.
```
- mkdir -p .ssh
- echo "$DEPLOY_PRIVATE_KEY_DEV" | tr -d '\r'  > .ssh/id_rsa
```

And in my  case - DEPLOY_PRIVATE_KEY_DEV was empty, so readFileSync return empty buffer.
But I don't really know why this error should occur even with an empty buffer.
